In [2]:
import numpy as np

list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))

Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list

In [4]:
print("list_:")

for element in list_:
    print(type(element))


print("\narray_list:")

for element in array_list:
    print(type(element))


list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

In [5]:
array_list = np.array(object = list_, dtype = int)

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [6]:
print("list_:")

for element in list_:
    print(type(element))


print("\narray_list:")

for element in array_list:
    print(type(element))

list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Even though the specified data type for array_list is int, when you print the data types of elements, the elements in list_ are still of type int (regular Python integers), while the elements in the modified array_list are of type numpy.int64 (NumPy integers). The specified data type in NumPy affects the internal representation of the array elements but does not change the Python type you observe when using type()

# Consider the below code to answer further questions:


In [10]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [13]:
# (i) shape

num_array.shape

(2, 3)

In [14]:
# (ii) size

num_array.size

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [17]:
import numpy as np


zero = np.zeros((3, 3))

print("3x3 Matrix ")
print(zero)


3x3 Matrix 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [18]:
import numpy as np

identity = np.eye(5)

# Print the result
print("5x5 Identity :")
print(identity)


5x5 Identity :
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
